# Generated by Django 5.1.3 on 2024-12-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bestellung', '0002_artikel_alter_lieferung_lieferant_lagerplatz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='bezeichung',
            field=models.CharField(max_length=250, verbose_name='Bezeichnung'),
        ),
    ]
